name: Merge to Main branch

on:
  push:
    branches:
    - main

jobs:
  build:  # Add a job name here
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./wrapper

    steps:
     # Run a terraform plan
    - name: Terraform Apply
      id: apply
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: terraform apply -var-file="../environments/main/main.tfvars" -auto-approve