name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

#Special permissions required for OIDC authentication

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./wrapper
    env:
      #this is needed since we are running terraform with read-only permissions
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

          # Run kics scan
    - name: KICS Github Action
      uses: Checkmarx/kics-github-action@v2.0.0
      with:
        path: .
        output: 'json,sarif'
        platform_type: terraform
        output-path: results-dir
        ignore_on_exit: results
        log-level: info

    - name: List files
      run: ls -la


    - name: Upload SARIF file
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./results-dir/results.sarif

 

