name: Terraform

on:
  push:
    branches:
    - main


jobs:
  terraform_plan:
    name: 'Terraform Plan'
    # if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./wrapper

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config=../environments/${{ github.base_ref }}/backend.json

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file=../environments/${{ github.base_ref }}/${{ github.base_ref }}.tfvars -out=plan.tfplan

    - name: Show Plan
      run: terraform show -no-color plan.tfplan > plan.txt

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: ./wrapper/plan.txt

    - name: Create Pull Request Review
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('./wrapper/plan.txt', 'utf8');
          const { owner, repo, number: pull_number } = context.issue;
          const review = await github.pulls.createReview({
            owner,
            repo,
            pull_number,
            body: `Terraform plan:\n\n\`\`\`\n${plan}\n\`\`\``,
            event: 'COMMENT',
          });

  terraform_apply:
    name: 'Terraform Apply'
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./wrapper

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config=../environments/${{ github.base_ref }}/backend.json

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
        path: ./wrapper

    - name: Terraform Apply
      run: terraform apply "plan.tfplan"