name: Terraform

# trigger manually
on:
  workflow_dispatch:
jobs:
  terraform_plan:
    name: 'Terraform Plan'
    # if: ${{ github.event_name == 'pull_request' }}
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./wrapper

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init -backend-config=../environments/main/backend.json

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file=../environments/main/main.tfvars -out=plan.tfplan

    - name: Show Plan
      run: terraform show -no-color plan.tfplan > plan.txt

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: ./wrapper/plan.txt
